### PR TITLE
Bump foldl dependency bound

### PR DESCRIPTION
**Pull request by parsonsmatt**
I built the library with the bumped bound and it worked for me.

Do you have any interest in putting this library in Stackage?

Thanks for the fantastic libraries :D

### CODE REVIEW

**Comment by Gabriel439** [comment]
Sure, I can put this on Stackage

**Comment by Gabriel439** [comment]
Also, are there any other additions you would like to make before I upload this to Hackage?  I have to upload this before I can add it to Stackage

**Comment by parsonsmatt** [comment]
I mostly just want the `left`, `right`, and `+++` combinators, and can't think of anything else I'd want at the moment. Thanks!

**Comment by Gabriel439** [comment]
Alright, I opened a pull request to add this to Stackage: https://github.com/fpco/stackage/pull/809

**Pull request merged**
